npx tsx query -$ '{"currency":"0x350fe2", "source_ref":""}' 
npx tsx query -$ '{"currency":"0x350fe2", "source_ref":"USDT"}' 
npx tsx query -$ '{"currency":"0x350fe2", "symbol":""}' 
npx tsx query -$ '{"currency": "0x7bf59d"}'
npx tsx query -$ '{"currency":"", "source_ref":"USDT"}' 
npx tsx query -$ '{"currency":"", "symbol":"USDT"}' 
npx tsx query -$ '{"symbol": "BMT"}'
npx tsx query -$ '{"symbol": "XRP"}'
npx tsx query -$ '{"symbol":"XRP"}'
npx tsx query -$ '{"symbol":"XRP-USDT"}'
npx tsx query -c '{"contract_type": "0xf667ea"}'
npx tsx query -c '{"contract_type":"0xf667ed"}' 
npx tsx query -c '{"contract_type": "0xf667ed"}'
npx tsx query -c '{"contract_type":"0xf667ed", "source_ref":""}' 
npx tsx query -c '{"source_ref":""}' 
npx tsx query -c '{"source_ref":"junk"}' 
npx tsx query -c '{"source_ref":"linear"}' 
npx tsx query -c '{"source_ref": "linear"}'
npx tsx query -c '{"source_ref": "SWAP"}'
npx tsx query -d '{"instrument":"0xcb42a5"}' 
npx tsx query -d '{"instrument":0xcb42a5}' 
npx tsx query -d '{"instrument": "0xe0705c"}'
npx tsx query -d '{"instrument":"cb42a5"}' 
npx tsx query -d '{"instrument":"x'cb42a5'"}' 
npx tsx query -d '{"symbol":"XRP"}' 
npx tsx query -d '{"symbol":"XRP-USDT"}' 
npx tsx query -i 
npx tsx query -i '{}'
npx tsx query -i '{}' 
npx tsx query -i '{"base_currency":"XRP"}'
npx tsx query -i '{"base_symbol":"XRP"}'
npx tsx query -i '{"currency":["0x00413b", "0x350fe2"]}'
npx tsx query -i '{"currency":["0x00413b", "0x350fe2"}'
npx tsx query -i '{"currency":"0x02033c"}'
npx tsx query -i '{"currency":["0x02033c", "0x350fe2"]}'
npx tsx query -i '{"currency": ["0x87ee80","0x350fe2"]}'
npx tsx query -i '{"instrument":"0x00000f"}'
npx tsx query -i '{"instrument":"0x4e3e8a"}'
npx tsx query -i '{"instrument": "0xcb42a5"}'
npx tsx query -i '{"instrument":"0xcb42a5"}'
npx tsx query -i '{"instrument": "0xe0705c"}'
npx tsx query -i '{}' '{"limit":5,"fromSymbol":"AV"}' 
npx tsx query -i '{}' '{"limit":5,"fromSymbol":"X"}' 
npx tsx query -i '{"quote_symbol":"USDT"}' 
npx tsx query -i '{"state":"Enabled"}'
npx tsx query -i '{"symbol":""}'
npx tsx query -i '{"symbol":"0x02033c"}'
npx tsx query -i '{"symbol":"1000000BABYDOGE"}'
npx tsx query -i '{"symbol":["1000000BABYDOGE"]}'
npx tsx query -i '{"symbol:"1000000BABYDOGE"]}'
npx tsx query -i '{"symbol:"1000000BABYDOGE"}'
npx tsx query -i '{"symbol": ["BMT", "USDT"]}'
npx tsx query -i '{"symbol":"btccc"}'
npx tsx query -i '{"symbol":"VRA"}'
npx tsx query -i '{"symbol":"XRP"}'
npx tsx query -i '{"symbol":"XRP"}' 
npx tsx query -i '{"symbol":["XRP-"]}'
npx tsx query -i '{"symbol":"XRP-BTC"}'
npx tsx query -i '{"symbol":["XRP-","BTC"]}'
npx tsx query -i '{"symbol":["XRP-BTC"]}'
npx tsx query -i '{"symbol":"XRP"}' '{"limit":5,"fromSymbol":"X"}'
npx tsx query -i '{"symbol":"XRP"}' '{"limit":5,"fromSymbol":"X"}' 
npx tsx query -i '{"symbol":"XRP","USDT"}'
npx tsx query -i '{"symbol":"XRP-USDT"}'
npx tsx query -i '{"symbol":"XRP-USDT"}' 
npx tsx query -i '{"symbol":["-XRP","USDT"]}'
npx tsx query -i '{"symbol":["XRP","USDT"]}'
npx tsx query -i '{"symbol":["XRP-","USDT"]}'
npx tsx query -i '{"symbol":["XRP-USDT"]}'
npx tsx query -K '{"active_collection":"true"}'
npx tsx query -K '{"active_collection":true}'
npx tsx query -K '{"state":"Enabled"}'
npx tsx query -K '{"symbol":"XRP"}'
npx tsx query -K '{"symbol":"XRP-"}'
npx tsx query -K '{"symbol":"XRP","timeframe": "15m"}'
npx tsx query -p '{"period":"0x68fe1d", "timeframe":"1m"}' 
npx tsx query -p '{"period":"0x68fe1d", "timeframe":"3m"}' 
npx tsx query -p '{"period": "0xe1e68b"}'
npx tsx query -p '{"period":"", "timeframe":""}' 
npx tsx query -p '{"period":"", "timeframe":"1m"}' 
npx tsx query -p '{"period":"", "timeframe":"3m"}' 
npx tsx query -p '{"timeframe": "1m"}'
npx tsx query -p '{"timeframe":"1m"}'
npx tsx query -p '{"timeframe": "1M"}'
npx tsx query -s '{"state": "Disabled"}'
npx tsx query -s '{"state": "Enabled"}'
npx tsx query -s '{"state":"Enabled"}'
npx tsx query -s '{"state":"Suspended"}'
npx tsx query -s '{"trade_state": "0x14e7c6"}'
npx tsx query -s '{"trade_state":"0x7c7ab8"}'
npx tsx query -s '{"trade_state":"0x7c7ab8", "state":"Disabled"}' 
npx tsx query -s '{"trade_state":"0x7c7ab8", "state":"Enabled"}' 
npx tsx query -s '{"trade_state":"", "state":""}' 
npx tsx query -s '{"trade_state":"", "state":"Disabled"}' 
npx tsx query -s '{"trade_state":"", "state":"Enabled"}' 
npx tsx query -s '{"trade_state":"", "state":"junk"}' 
npx tsx query -t '{"instrument_type": "0xc685bf"}'
npx tsx query -t '{"instrument_type":"0xf6fdee", "source_ref":""}' 
npx tsx query -t '{"instrument_type":"0xf6fdee", "source_ref":"SWAP"}' 
npx tsx query -t '{"instrument_type":"", "source_ref":""}' 
npx tsx query -t '{"instrument_type":"", "source_ref":"SWAP"}' 
npx tsx query -t '{"source_ref": "Linear"}'
npx tsx query -t '{"source_ref": "SWAP"}'
